In [38]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [39]:
data=pd.read_csv("Sales_add.csv")

In [40]:
data.head()

Month      Region      Manager  Sales_before_digital_add(in $)  \
0  Month-1  Region - A  Manager - A                          132921   
1  Month-2  Region - A  Manager - C                          149559   
2  Month-3  Region - B  Manager - A                          146278   
3  Month-4  Region - B  Manager - B                          152167   
4  Month-5  Region - C  Manager - B                          159525   

   Sales_After_digital_add(in $)  
0                         270390  
1                         223334  
2                         244243  
3                         231808  
4                         258402

In [41]:
data.isna().sum()

Month                             0
Region                            0
Manager                           0
Sales_before_digital_add(in $)    0
Sales_After_digital_add(in $)     0
dtype: int64

In [42]:
data.describe()

Sales_before_digital_add(in $)  Sales_After_digital_add(in $)
count                       22.000000                      22.000000
mean                    149239.954545                  231123.727273
std                      14844.042921                   25556.777061
min                     130263.000000                  187305.000000
25%                     138087.750000                  214960.750000
50%                     147444.000000                  229986.500000
75%                     157627.500000                  250909.000000
max                     178939.000000                  276279.000000

# checking whether there is any increase in sales after stepping into digital marketing.

In [43]:
data[['Sales_before_digital_add(in $)','Sales_After_digital_add(in $)']]

Sales_before_digital_add(in $)  Sales_After_digital_add(in $)
0                           132921                         270390
1                           149559                         223334
2                           146278                         244243
3                           152167                         231808
4                           159525                         258402
5                           137163                         256948
6                           130625                         222106
7                           131140                         230637
8                           171259                         226261
9                           141956                         193735
10                          159339                         203175
11                          178939                         276279
12                          145062                         205180
13                          151514                         253131
14                          147463                         229336
15                          177195                         187305
16                          140862                         234908
17                          167996                         191517
18                          132135                         227040
19                          152493                         212579
20                          147425                         263388
21                          130263                         243020

In [44]:
data[['Sales_before_digital_add(in $)','Sales_After_digital_add(in $)']].mean()

Sales_before_digital_add(in $)    149239.954545
Sales_After_digital_add(in $)     231123.727273
dtype: float64

In [45]:
class1=data['Sales_before_digital_add(in $)']
class2=data['Sales_After_digital_add(in $)']

In [46]:
#finding varience
print(np.var(class1),np.var(class2))

210329900.67975205 623460269.4710745


In [47]:
# Null hypothesis: There is no increase in sales after stepping into digital marketing
# Alternative hypothesis: There is  increase in sales after stepping into digital marketing.

In [48]:
from scipy.stats import ttest_ind
from scipy import stats

In [49]:
class1_mean = np.mean(class1)
class2_mean = np.mean(class2)

In [50]:
print("Sales before digital_mean value:",class1_mean)
print("Sales after digital_mean value:",class2_mean)

Sales before digital_mean value: 149239.95454545456
Sales after digital_mean value: 231123.72727272726


In [51]:
class1_std = np.std(class1)
class2_std = np.std(class2)

In [52]:
print("Sales before digital_std value:",class1_std)
print("Sales after digital_std value:",class2_std)

Sales before digital_std value: 14502.754934141032
Sales after digital_std value: 24969.18639986242


In [53]:
ttest,p_value = stats.ttest_ind(class1,class2)
print(ttest,p_value)

-12.995084451110877 2.614368006904645e-16


In [54]:
if p_value <0.05:
  print("we reject null hypothesis")
else:
  print("we accept null hypothesis")

we reject null hypothesis


Inference: There is increase in sales after stepping into digital marketting.

# checking dependency between the features “Region” and “Manager”

In [55]:
data1=data.sort_values(by=['Manager'],ascending=False)[['Manager','Region']]
data1

Manager      Region
21  Manager - C  Region - A
6   Manager - C  Region - C
8   Manager - C  Region - B
10  Manager - C  Region - B
1   Manager - C  Region - A
16  Manager - C  Region - A
15  Manager - B  Region - A
3   Manager - B  Region - B
4   Manager - B  Region - C
5   Manager - B  Region - A
19  Manager - B  Region - A
9   Manager - B  Region - C
17  Manager - B  Region - C
20  Manager - A  Region - B
18  Manager - A  Region - B
0   Manager - A  Region - A
14  Manager - A  Region - C
13  Manager - A  Region - A
12  Manager - A  Region - B
7   Manager - A  Region - A
2   Manager - A  Region - B
11  Manager - A  Region - A

In [56]:
import pandas as pd
from scipy import stats
contingency_table=pd.crosstab(data["Manager"],data["Region"])
print(contingency_table)

Region       Region - A  Region - B  Region - C
Manager                                        
Manager - A           4           4           1
Manager - B           3           1           3
Manager - C           3           2           1


In [57]:
# Null hypothesis: There is no dependency between Manager and Region
# Alternative hypothesis:  There is dependency between Manager and Region

In [58]:
Observed_Values = contingency_table.values 
print("Observed Values :-\n",Observed_Values)

Observed Values :-
 [[4 4 1]
 [3 1 3]
 [3 2 1]]


In [59]:
b=stats.chi2_contingency(contingency_table)
Expected_Values = b[3]
print("Expected Values :-\n",Expected_Values)

Expected Values :-
 [[4.09090909 2.86363636 2.04545455]
 [3.18181818 2.22727273 1.59090909]
 [2.72727273 1.90909091 1.36363636]]


In [60]:
no_of_rows=len(contingency_table.iloc[0:3,0])
no_of_columns=len(contingency_table.iloc[0,0:3])
ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:-",ddof)

Degree of Freedom:- 4


In [61]:
alpha = 0.05

In [62]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(Observed_Values,Expected_Values)])
chi_square_statistic=chi_square[0]+chi_square[1]+chi_square[2]
print("chi-square statistic:-",chi_square_statistic)
critical_value=chi2.ppf(q=1-alpha,df=ddof)
print('critical_value:',critical_value)

chi-square statistic:- 3.050566893424036
critical_value: 9.487729036781154


In [63]:
p_value=1-chi2.cdf(x=chi_square_statistic,df=ddof)
print('p-value:',p_value)
print('Significance level: ',alpha)
print('Degree of Freedom: ',ddof)
print('chi-square statistic:',chi_square_statistic)
print('critical_value:',critical_value)
print('p-value:',p_value)

p-value: 0.5493991051158094
Significance level:  0.05
Degree of Freedom:  4
chi-square statistic: 3.050566893424036
critical_value: 9.487729036781154
p-value: 0.5493991051158094


In [64]:
if chi_square_statistic>=critical_value:
    print("Reject H0,There is a relationship between 2 categorical variables")
else:
    print("Retain H0,There is no relationship between 2 categorical variables")

Retain H0,There is no relationship between 2 categorical variables


Inference: There is no dependency between Manager and Region.